### ISSUE TITLE
Feedback new message

### ISSUE THREAD

**Issue by asharijuang** [Qiscus-Integration/android-multichannel-widget#3]
posisi di tengah chat, tidak ada popup pemberitahuan kalo ada message baru

**Comment by asharijuang** [comment]
mas @mmnuradityo issue ini dan https://github.com/Qiscus-Integration/android-multichannel-widget/issues/1
kok berbanding terbalik ya?

maksudku kl mau langsung scroll ke bawah ga perlu ada pemberitahuan, dan sebaliknya

**Comment by mmnuradityo** [comment]
sudah di tambahkan di branch multichannel
